### ISSUE TITLE
Error Timbrado NQ17

### ISSUE THREAD

**Issue by AnaGGM** [AARP41298/CeaIncTest#421]
Beun dia @AARP41298 @MayorgaDev .

Se detectaron los siguientes errores en los timbrados de la NQ17:

**PUNTO 1:** Diferencia en decimales

**Mensaje Error:** 
 
![image](https://github.com/AARP41298/CeaIncTest/assets/149442913/1c318189-56e7-4d38-a080-b512a7c7104e)

**Ejemplo:** Empleado **180252**

![image](https://github.com/AARP41298/CeaIncTest/assets/149442913/8f2f8c4c-5ded-43b5-8d3c-e29052f9cd9f)

**(NODO DEDUCCIONES)**
<nomina12:Deduccion TipoDeduccion="006" Clave="2204" Concepto="FALTA POR INCAPACIDAD DE RIESGO DE TRABAJO" **Importe="10110.94"**/>

**(NODO INCAPACIDADES)**
<nomina12:Incapacidad TipoIncapacidad="01" **ImporteMonetario="10110.95"** DiasIncapacidad="15"/>

**Relación Empleados:**
NQ172023_601923
NQ172023_110607
NQ172023_010004
NQ172023_180252
NQ172023_200034

**PUNTO 2:** Falta el nodo de "Incapacidades"

**Mensaje Error:**
![image](https://github.com/AARP41298/CeaIncTest/assets/149442913/47c3090c-136a-4be0-b71f-90c37fac2856)

Ejemplo: Empleado 170046

**INFOTEC**
![image](https://github.com/AARP41298/CeaIncTest/assets/149442913/c6d53d8f-3630-47bf-980a-7c8e0eb9b674)

**SAP**

![image](https://github.com/AARP41298/CeaIncTest/assets/149442913/812d45fa-d556-4593-8e5e-6807407395af)

**Relación Empleados:**

NQ172023_170046
NQ172023_990551
NQ172023_990507
NQ172023_060048
NQ172023_110401
NQ172023_050041
NQ172023_990518
NQ172023_990402
NQ172023_130124
NQ172023_050068
NQ172023_990400
NQ172023_990634

**Comment by MayorgaDev** [comment]
El ajuste fue unicamente a nivel código, no es necesario el modificar registros en base de datos, se modifico solo Backend.

**Comment by AnaGGM** [comment]
Se valido en ambiente Prep y se realizó prueba de timbrado en ambiente de pruebas. Los resultados fueron correctos.

![image](https://github.com/AARP41298/CeaIncTest/assets/149442913/37fa766d-428f-4ef3-aaf7-e043ef30516a)

Se notificó para que el cambio se pasará al ambiente productivo (@MayorgaDev ). Finalmente se bajaron los cambios en el servidor (solo Back - JCZ).

Gracias.

**Comment by AnaGGM** [comment]
Validación ok
